# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Wes/Desktop/alm_done/FDP.cache/wt [current_project]
set_property parent.project_path C:/Users/Wes/Desktop/alm_done/FDP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Wes/Desktop/alm_done/FDP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/res/weights.coe
add_files C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/res/00.coe
read_verilog -library xil_defaultlib {
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/Oled_Display.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/ball_movement_controller.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/ball_movement_system_top.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/ball_tracking_system.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/charge_details.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/clk_change.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/collision_detector_enhanced.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/colour_menu.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/debouncer.v
  {C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/map_generator end detect/map_generator.srcs/sources_1/imports/end_hole_detect.v}
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/end_menu.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/map_generator/map_generator.srcs/sources_1/new/friction_area.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/friction_controller.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/friction_coulomb_q8_8.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/game_menu.v
  {C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/map_generator end detect/map_generator.srcs/sources_1/new/inside_map.v}
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/led_charging.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/led_pwm.v
  {C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/map_generator end detect/map_generator.srcs/sources_1/new/map_generator.v}
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/ms_pulse.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/oled_graphics_renderer_debug.v
  {C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/map_generator end detect/map_generator.srcs/sources_1/imports/Desktop/random_blob_generator/random_blob_generator.srcs/sources_1/new/randomiser.v}
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/secret_sequence.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/seven_segment_chase.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Users/user/Downloads/FDP.xpr/FDP/FDP.srcs/sources_1/new/sevenseg.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/start_menu.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/trig_calculator.v
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/trig_lut_first_quadrant.v
  {C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/map_generator end detect/map_generator.srcs/sources_1/new/unpack_obstacles.v}
  {C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/map_generator end detect/map_generator.srcs/sources_1/new/vertical_horizontal_detect.v}
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/new/Top_Student.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/Mouse_Control.vhd
  C:/Users/Wes/Desktop/alm_done/FDP.srcs/sources_1/imports/Desktop/Ps2Interface.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Wes/Desktop/alm_done/FDP.srcs/constrs_1/new/my_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Wes/Desktop/alm_done/FDP.srcs/constrs_1/new/my_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
